### ISSUE TITLE
Bin Gespannt auf das plugin wann ist es ca fertig?

### ISSUE THREAD

**Issue by Gtafgu** [tim03we/Bedwars-OLD#1]

**Comment by tim03we** [comment]
I don't know when it'll be finished. It is a small side project that I start. But there should be regular updates if nothing gets in my way.

**Comment by DeeRenjie** [comment]
I would like nukkit to have a wake-up war plug-in. At present, there is no such plug-in.
我很希望nukkit有起床战争插件，目前来说都没有任何这类的插件。
