### ISSUE TITLE
pls update

### ISSUE THREAD

**Issue by Papadoubulus** [tim03we/Bedwars-OLD#2]
Bitte update das wäre ehre

**Comment by tim03we** [comment]
Es wird evtl. ein neues kommen.

**Comment by Papadoubulus** [comment]
Geil

**Comment by tim03we** [comment]
Bei weiteren Fragen kannst du mich über Discord erreichen. 

--- Tim ---#5056

**Comment by tim03we** [comment]
Glaube ich habe gerade deine FA abgelehnt. Schick nochmal eine.
