### ISSUE TITLE
(question) Does this plugin operate normally?

### ISSUE THREAD

**Issue by JuChanMin** [tim03we/Bedwars-OLD#3]
Using the command, I can only see pop-ups or empty chats.
Can I proceed with the game with this plugin? :o 
(I'm Sorry, I don't know how to read plugin sources. :c)

**Comment by tim03we** [comment]
The plugin was a start. It will not be continued. I have one of my own, but this one is private. Sorry.

**Comment by JuChanMin** [comment]
Oooh ok
Thank you for reply ;)
